version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
  web:
    build: ../
    restart: always
    volumes:
      - ./deploy_in_container.py:/app/infra/deploy_in_container.py
      - static_value:/app/static
    depends_on:
      - db
    command: python3 infra/deploy_in_container.py
    env_file:
      - ../.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - web

volumes:
  static_value:
  postgres_data:
